name: pytest on Unix OS

on:
  pull_request:
    branches:
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

jobs:
  pytest:
    name: pytest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_ver: [3.7, 3.8]
        exclude:
          # Conda environment fails with Python 3.8 on macOS
          - os: macos-latest
            python_ver: 3.8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-py-${{ matrix.python_ver }}-${{ hashFiles('environment.yml') }}
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: geoapps
          python-version: ${{ matrix.python_ver }}
          channel-priority: strict
          environment-file: environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: pytest
        shell: bash -l {0}
        run: |
          conda activate geoapps
          python --version
          conda install pytest pytest-cov
          pytest --cov=geoapps --cov-report=xml --cov-branch
